export const videosData = [
  {
    id: "3",
    thumbnail: require("../assets/images/image1.png"),
    video: require("../assets/videos/1.mp4"),
    title: "Sending Firebase Data Messages to Expo: iOS",
    username: "Expo",
    avatar: require("../assets/images/avatar.jpg"),
    views: "189",
    published: "6 days ago",
  },
  {
    id: "1",
    thumbnail: require("../assets/images/image2.png"),
    video: require("../assets/videos/2.mp4"),
    title: "React Native Image Picker Tutorial",
    username: "Expo",
    avatar: require("../assets/images/avatar.jpg"),
    views: "63",
    published: "6 days ago",
  },
  {
    id: "2",
    thumbnail: require("../assets/images/image3.png"),
    video: require("../assets/videos/1.mp4"),
    title: "PIXI.js in React Native for beginners",
    username: "Expo",
    avatar: require("../assets/images/avatar.jpg"),
    views: "216",
    published: "6 days ago",
  },
  {
    id: "4",
    thumbnail: require("../assets/images/image1.png"),
    video: require("../assets/videos/2.mp4"),
    title: "Permissions in React Native for absolute beginners",
    username: "Expo",
    avatar: require("../assets/images/avatar.jpg"),
    views: "273",
    published: "6 days ago",
  },
];
